apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-1
spec:
  replicas: 4
  minReadySeconds: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: nginx_pod_1
  template:
    metadata:
      labels:
        app: nginx_pod_1
    spec:
      containers:
      - name: simple-http
        image: 255657835453.dkr.ecr.ap-northeast-2.amazonaws.com/pri_repo:latest
        ports:
        - name: http
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-service
spec:
  type: LoadBalancer
  selector:
    app: nginx_pod_1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
