apiVersion: apps/v1 
kind: Deployment
metadata:
  name: nginx
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template: 
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: 255657835453.dkr.ecr.ap-northeast-2.amazonaws.com/pri_repo
        ports:
        - containerPort: 80
