apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-1
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx_pod_1
  template:
    metadata:
      labels:
        app: nginx_pod_1
    spec:
      containers:
      - name: simple-http
        image: 255657835453.dkr.ecr.ap-northeast-2.amazonaws.com/pri_repo:latest
        ports:
        - name: http
          containerPort: 80
